# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.12.21
_src_path: gh:scientific-python/cookie
backend: hatch
email: alanlujan91@gmail.com
full_name: Alan Lujan
license: MIT
org: alanlujan91
project_name: scf-tools
project_short_description:
  Tools to download and analyze the Survey of Consumer Finances.
url: https://github.com/alanlujan91/scf-tools
vcs: true
